# Generated by Django 4.0.2 on 2026-07-01 03:21

import core.security.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('author', models.CharField(max_length=120, verbose_name='Autor')),
                ('image', core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Logo')),
                ('icon', models.CharField(max_length=500, verbose_name='Icono FontAwesome')),
                ('layout', models.IntegerField(choices=[(1, 'Vertical'), (2, 'Horizontal')], default=1, verbose_name='Diseño')),
                ('card', models.CharField(choices=[(' ', 'clear'), ('card-primary', 'card-primary'), ('card-blue', 'card-blue'), ('card-indigo', 'card-indigo'), ('card-cyan', 'card-cyan'), ('card-danger', 'card-danger'), ('card-dark', 'card-dark'), ('card-fuchsia', 'card-fuchsia'), ('card-gray', 'card-gray'), ('card-gray-dark', 'card-gray-dark'), ('card-green', 'card-green'), ('card-info', 'card-info'), ('card-lime', 'card-lime'), ('card-maroon', 'card-maroon'), ('card-navy', 'card-navy'), ('card-olive', 'card-olive'), ('card-orange', 'card-orange'), ('card-outline', 'card-outline'), ('card-pink', 'card-pink'), ('card-purple', 'card-purple'), ('card-red', 'card-red'), ('card-secondary', 'card-secondary'), ('card-success', 'card-success'), ('card-teal', 'card-teal'), ('card-warning', 'card-warning'), ('card-white', 'card-white'), ('card-yellow', 'card-yellow'), ('card-outline card-primary', 'card-outline card-primary'), ('card-outline card-blue', 'card-outline card-blue'), ('card-outline card-indigo', 'card-outline card-indigo'), ('card-outline card-cyan', 'card-outline card-cyan'), ('card-outline card-danger', 'card-outline card-danger'), ('card-outline card-dark', 'card-outline card-dark'), ('card-outline card-fuchsia', 'card-outline card-fuchsia'), ('card-outline card-gray', 'card-outline card-gray'), ('card-outline card-gray-dark', 'card-outline card-gray-dark'), ('card-outline card-green', 'card-outline card-green'), ('card-outline card-info', 'card-outline card-info'), ('card-outline card-lime', 'card-outline card-lime'), ('card-outline card-maroon', 'card-outline card-maroon'), ('card-outline card-navy', 'card-outline card-navy'), ('card-outline card-olive', 'card-outline card-olive'), ('card-outline card-orange', 'card-outline card-orange'), ('card-outline card-outline', 'card-outline card-outline'), ('card-outline card-pink', 'card-outline card-pink'), ('card-outline card-purple', 'card-outline card-purple'), ('card-outline card-red', 'card-outline card-red'), ('card-outline card-secondary', 'card-outline card-secondary'), ('card-outline card-success', 'card-outline card-success'), ('card-outline card-teal', 'card-outline card-teal'), ('card-outline card-warning', 'card-outline card-warning'), ('card-outline card-white', 'card-outline card-white'), ('card-outline card-yellow', 'card-outline card-yellow')], default=' ', max_length=50, verbose_name='Card')),
                ('navbar', models.CharField(choices=[('navbar-dark navbar-primary', 'navbar-primary'), ('navbar-dark navbar-secondary', 'navbar-secondary'), ('navbar-dark navbar-info', 'navbar-info'), ('navbar-dark navbar-success', 'navbar-success'), ('navbar-dark navbar-danger', 'navbar-danger'), ('navbar-dark navbar-indigo', 'navbar-indigo'), ('navbar-dark navbar-purple', 'navbar-purple'), ('navbar-dark navbar-pink', 'navbar-pink'), ('navbar-dark navbar-navy', 'navbar-navy'), ('navbar-dark navbar-lightblue', 'navbar-lightblue'), ('navbar-dark navbar-teal', 'navbar-teal'), ('navbar-dark navbar-cyan', 'navbar-cyan'), ('navbar-dark navbar-dark', 'navbar-dark'), ('navbar-dark navbar-gray-dark', 'navbar-gray-dark'), ('navbar-dark navbar-gray', 'navbar-gray'), ('navbar-light navbar-light', 'navbar-light'), ('navbar-light navbar-warning', 'navbar-warning'), ('navbar-light navbar-white', 'navbar-white'), ('navbar-light navbar-orange', 'navbar-orange')], default='navbar-dark navbar-primary', max_length=50, verbose_name='Navbar')),
                ('brand_logo', models.CharField(choices=[(' ', 'clear'), ('navbar-primary', 'navbar-primary'), ('navbar-secondary', 'navbar-secondary'), ('navbar-info', 'navbar-info'), ('navbar-success', 'navbar-success'), ('navbar-danger', 'navbar-danger'), ('navbar-indigo', 'navbar-indigo'), ('navbar-purple', 'navbar-purple'), ('navbar-pink', 'navbar-pink'), ('navbar-navy', 'navbar-navy'), ('navbar-lightblue', 'navbar-lightblue'), ('navbar-teal', 'navbar-teal'), ('navbar-cyan', 'navbar-cyan'), ('navbar-dark', 'navbar-dark'), ('navbar-gray-dark', 'navbar-gray-dark'), ('navbar-gray', 'navbar-gray'), ('navbar-light', 'navbar-light'), ('navbar-warning', 'navbar-warning'), ('navbar-white', 'navbar-white'), ('navbar-orange', 'navbar-orange')], default=' ', max_length=50, verbose_name='Brand Logo')),
                ('sidebar', models.CharField(choices=[('sidebar-dark-primary', 'sidebar-dark-primary'), ('sidebar-dark-warning', 'sidebar-dark-warning'), ('sidebar-dark-info', 'sidebar-dark-info'), ('sidebar-dark-danger', 'sidebar-dark-danger'), ('sidebar-dark-success', 'sidebar-dark-success'), ('sidebar-dark-indigo', 'sidebar-dark-indigo'), ('sidebar-dark-lightblue', 'sidebar-dark-lightblue'), ('sidebar-dark-navy', 'sidebar-dark-navy'), ('sidebar-dark-purple', 'sidebar-dark-purple'), ('sidebar-dark-fuchsia', 'sidebar-dark-fuchsia'), ('sidebar-dark-pink', 'sidebar-dark-pink'), ('sidebar-dark-maroon', 'sidebar-dark-maroon'), ('sidebar-dark-orange', 'sidebar-dark-orange'), ('sidebar-dark-lime', 'sidebar-dark-lime'), ('sidebar-dark-teal', 'sidebar-dark-teal'), ('sidebar-dark-olive', 'sidebar-dark-olive'), ('sidebar-light-primary', 'sidebar-light-primary'), ('sidebar-light-warning', 'sidebar-light-warning'), ('sidebar-light-info', 'sidebar-light-info'), ('sidebar-light-danger', 'sidebar-light-danger'), ('sidebar-light-success', 'sidebar-light-success'), ('sidebar-light-indigo', 'sidebar-light-indigo'), ('sidebar-light-lightblue', 'sidebar-light-lightblue'), ('sidebar-light-navy', 'sidebar-light-navy'), ('sidebar-light-purple', 'sidebar-light-purple'), ('sidebar-light-fuchsia', 'sidebar-light-fuchsia'), ('sidebar-light-pink', 'sidebar-light-pink'), ('sidebar-light-maroon', 'sidebar-light-maroon'), ('sidebar-light-orange', 'sidebar-light-orange'), ('sidebar-light-lime', 'sidebar-light-lime'), ('sidebar-light-teal', 'sidebar-light-teal'), ('sidebar-light-olive', 'sidebar-light-olive')], default='sidebar-dark-primary', max_length=50, verbose_name='Sidebar')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'permissions': (('view_dashboard', 'Can view Dashboard'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('hour', models.TimeField(default=datetime.datetime.now)),
                ('remote_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('http_user_agent', models.CharField(blank=True, max_length=150, null=True)),
                ('archive', core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path)),
            ],
            options={
                'verbose_name': 'Respaldos de BD',
                'verbose_name_plural': 'Respaldo de BD',
                'permissions': (('view_database_backups', 'Can view Respaldo de BD'), ('add_database_backups', 'Can add Respaldo de BD'), ('delete_database_backups', 'Can delete Respaldo de BD')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GroupModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Grupo Módulo',
                'verbose_name_plural': 'Grupo Módulos',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Icono')),
                ('image', core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('icon', models.CharField(max_length=30, unique=True, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Tipo de Módulo',
                'verbose_name_plural': 'Tipos de Módulos',
                'permissions': (('view_module_type', 'Can view Tipo de Módulo'), ('add_module_type', 'Can add Tipo de Módulo'), ('change_module_type', 'Can change Tipo de Módulo'), ('delete_module_type', 'Can delete Tipo de Módulo')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('hour', models.TimeField(default=datetime.datetime.now)),
                ('remote_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('http_user_agent', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Acceso de Usuario',
                'verbose_name_plural': 'Acceso de Usuarios',
                'permissions': (('view_user_access', 'Can view Acceso del usuario'), ('delete_user_access', 'Can delete Acceso del usuario')),
                'default_permissions': (),
            },
        ),
    ]
