# Generated by Django 4.2.30 on 2026-09-01 01:36

import core.security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='databasebackups',
            name='archive',
            field=core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
    ]
