# Generated by Django 4.2.30 on 2026-09-03 03:06

import core.security.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('security', '0003_alter_dashboard_image_alter_databasebackups_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='databasebackups',
            name='archive',
            field=core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
        migrations.CreateModel(
            name='GroupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_cash_register', models.BooleanField(default=False, verbose_name='Requiere apertura y cierre de caja')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='auth.group')),
            ],
            options={
                'verbose_name': 'Configuración de Grupo',
                'verbose_name_plural': 'Configuraciones de Grupo',
                'default_permissions': (),
            },
        ),
    ]
