# Generated by Django 4.2.30 on 2026-09-06 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_dashboard_image_alter_databasebackups_archive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databasebackups',
            options={'default_permissions': (), 'permissions': (('view_database_backups', 'Can view Respaldo de BD'), ('add_database_backups', 'Can add Respaldo de BD'), ('delete_database_backups', 'Can delete Respaldo de BD'), ('restore_database_backups', 'Can restore Respaldo de BD')), 'verbose_name': 'Respaldos de BD', 'verbose_name_plural': 'Respaldo de BD'},
        ),
    ]
