# Generated by Django 4.2.30 on 2026-09-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_alter_databasebackups_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackups',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id del archivo en Google Drive'),
        ),
        migrations.AddField(
            model_name='databasebackups',
            name='google_drive_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Enlace en Google Drive'),
        ),
        migrations.AddField(
            model_name='databasebackups',
            name='google_drive_upload_error',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Error al subir a Google Drive'),
        ),
    ]
