# Generated by Django 4.2.30 on 2026-09-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_databasebackups_google_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
