# Generated by Django 4.0.2 on 2026-07-01 03:21

import core.security.fields
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant.scheme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, verbose_name='Número de RUC')),
                ('business_name', models.CharField(max_length=50, verbose_name='Razón social')),
                ('tradename', models.CharField(max_length=50, verbose_name='Nombre Comercial')),
                ('main_address', models.CharField(max_length=200, verbose_name='Dirección del Establecimiento Matriz')),
                ('establishment_address', models.CharField(max_length=200, verbose_name='Dirección del Establecimiento Emisor')),
                ('establishment_code', models.CharField(max_length=3, verbose_name='Código del Establecimiento Emisor')),
                ('issuing_point_code', models.CharField(max_length=3, verbose_name='Código del Punto de Emisión')),
                ('special_taxpayer', models.CharField(max_length=13, verbose_name='Contribuyente Especial (Número de Resolución)')),
                ('obligated_accounting', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Obligado a Llevar Contabilidad')),
                ('image', core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Logotipo de la empresa')),
                ('environment_type', models.PositiveIntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCIÓN')], default=1, verbose_name='Tipo de Ambiente')),
                ('emission_type', models.PositiveIntegerField(choices=[(1, 'Emisión Normal')], default=1, verbose_name='Tipo de Emisión')),
                ('retention_agent', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Agente de Retención')),
                ('regimen_rimpe', models.CharField(blank=True, choices=[('', 'Regimen General'), ('CONTRIBUYENTE RÉGIMEN RIMPE', 'Rimpe Emprendedor'), ('CONTRIBUYENTE NEGOCIO POPULAR - RÉGIMEN RIMPE', 'Rimpe Negocio Popular')], default='', max_length=50, null=True, verbose_name='Regimen Tributario')),
                ('mobile', models.CharField(max_length=10, verbose_name='Teléfono celular')),
                ('phone', models.CharField(max_length=9, verbose_name='Teléfono convencional')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('website', models.CharField(max_length=250, verbose_name='Dirección de página web')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('iva', models.DecimalField(decimal_places=2, default=15.0, max_digits=9, verbose_name='IVA')),
                ('vat_percentage', models.IntegerField(choices=[(0, '0%'), (2, '12%'), (3, '14%'), (4, '15%'), (5, '5%'), (6, 'No Objeto de Impuesto'), (7, 'Exento de IVA'), (8, 'IVA diferenciado'), (10, '13%')], default=4, verbose_name='Porcentaje del IVA')),
                ('electronic_signature', core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='Firma electrónica (Archivo P12)')),
                ('electronic_signature_key', models.CharField(max_length=100, verbose_name='Clave de firma electrónica')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=30, verbose_name='Servidor de correo')),
                ('email_port', models.IntegerField(default=587, verbose_name='Puerto del servidor de correo')),
                ('email_host_user', models.CharField(max_length=100, verbose_name='Username del servidor de correo')),
                ('email_host_password', models.CharField(max_length=30, verbose_name='Password del servidor de correo')),
                ('schema_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del esquema')),
                ('active', models.BooleanField(default=True, verbose_name='Estado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.plan', verbose_name='Plan de facturación')),
                ('scheme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant.scheme', verbose_name='Esquema')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
