# Generated by Django 4.0.2 on 2026-08-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin del plan'),
        ),
        migrations.AddField(
            model_name='company',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del plan'),
        ),
    ]
