# Generated by Django 4.0.2 on 2026-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_company_plan_end_date_company_plan_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan_expiration_notified',
            field=models.BooleanField(default=False, verbose_name='Notificación de vencimiento enviada'),
        ),
        migrations.AddField(
            model_name='company',
            name='representative_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre del representante legal'),
        ),
        migrations.AddField(
            model_name='company',
            name='representative_position',
            field=models.CharField(blank=True, default='Representante Legal', max_length=100, verbose_name='Cargo del representante'),
        ),
    ]
