# Generated by Django 4.2.30 on 2026-09-01 17:26

import core.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_alter_company_electronic_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicInvoicingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100, verbose_name='Nombre del sistema')),
                ('ruc', models.CharField(max_length=13, verbose_name='RUC del proveedor')),
                ('website', models.CharField(max_length=250, verbose_name='Sitio web')),
            ],
            options={
                'verbose_name': 'Proveedor de Facturación Electrónica',
                'verbose_name_plural': 'Proveedor de Facturación Electrónica',
                'permissions': (('view_electronicinvoicingprovider', 'Can view Proveedor de Facturación Electrónica'), ('change_electronicinvoicingprovider', 'Can change Proveedor de Facturación Electrónica')),
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='electronic_signature',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='Firma electrónica (Archivo P12)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Logotipo de la empresa'),
        ),
    ]
