# Generated by Django 4.2.30 on 2026-09-05 22:53

import core.security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_electronicinvoicingprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.UploadTo(None, None), verbose_name='Logo'),
        ),
    ]
