# Generated by Django 4.2.30 on 2026-09-06 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_electronicinvoicingprovider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='backup_schedule_enabled',
            field=models.BooleanField(default=False, verbose_name='Respaldo automático habilitado'),
        ),
        migrations.AddField(
            model_name='company',
            name='backup_schedule_frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal')], default='weekly', max_length=10, verbose_name='Frecuencia del respaldo'),
        ),
        migrations.AddField(
            model_name='company',
            name='backup_schedule_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución automática'),
        ),
        migrations.AddField(
            model_name='company',
            name='backup_schedule_time',
            field=models.TimeField(default=datetime.time(2, 0), verbose_name='Hora del respaldo'),
        ),
        migrations.AddField(
            model_name='company',
            name='backup_schedule_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Día de la semana (respaldo semanal)'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_drive_account_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta de Google Drive conectada'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carpeta de Google Drive'),
        ),
        migrations.AddField(
            model_name='company',
            name='google_drive_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token de Google Drive'),
        ),
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='backup_schedule_enabled',
            field=models.BooleanField(default=False, verbose_name='Respaldo automático habilitado'),
        ),
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='backup_schedule_frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal')], default='weekly', max_length=10, verbose_name='Frecuencia del respaldo'),
        ),
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='backup_schedule_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución automática'),
        ),
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='backup_schedule_time',
            field=models.TimeField(default=datetime.time(2, 0), verbose_name='Hora del respaldo'),
        ),
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='backup_schedule_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Día de la semana (respaldo semanal)'),
        ),
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='google_drive_account_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta de Google Drive conectada'),
        ),
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carpeta de Google Drive'),
        ),
        migrations.AddField(
            model_name='electronicinvoicingprovider',
            name='google_drive_refresh_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token de Google Drive'),
        ),
    ]
