# Generated by Django 4.2.30 on 2026-09-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_company_backup_schedule_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_purchase_settlement',
            field=models.BooleanField(default=True, verbose_name='Habilitar Liquidación de Compra'),
        ),
        migrations.AddField(
            model_name='company',
            name='enable_ticket_sale',
            field=models.BooleanField(default=True, verbose_name='Habilitar Ticket de Venta'),
        ),
    ]
