# Generated by Django 4.2.30 on 2026-09-06 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_company_enable_purchase_settlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_auto_authorization_enabled',
            field=models.BooleanField(default=True, verbose_name='Autorización automática de facturas pendientes habilitada'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_auto_authorization_last_run',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución automática de autorización de facturas'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_auto_authorization_time',
            field=models.TimeField(default=datetime.time(23, 50), verbose_name='Hora de autorización automática de facturas pendientes'),
        ),
    ]
