# Generated by Django 4.2.30 on 2026-09-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_company_invoice_auto_authorization_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_sale_voucher_type',
            field=models.CharField(choices=[('01', 'FACTURA'), ('08', 'TICKET DE VENTA'), ('03', 'LIQUIDACIÓN DE COMPRA')], default='01', max_length=10, verbose_name='Comprobante por defecto al crear una venta'),
        ),
    ]
