# Generated by Django 4.2.30 on 2026-10-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_company_default_sale_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='retention_agent_resolution',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='N° de resolución de agente de retención'),
        ),
    ]
