# Generated by Django 4.2.30 on 2026-10-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_company_retention_agent_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='keep_accounting_module',
            field=models.BooleanField(default=False, verbose_name='Activar módulo de Contabilidad aunque no esté obligado'),
        ),
    ]
