# Generated by Django 4.2.30 on 2026-09-01 17:45

import core.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=150, verbose_name='Título principal')),
                ('hero_subtitle', models.CharField(blank=True, default='', max_length=300, verbose_name='Subtítulo')),
                ('hero_image', core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen principal')),
                ('footer_text', models.CharField(blank=True, default='', max_length=300, verbose_name='Texto del footer')),
                ('facebook_url', models.CharField(blank=True, default='', max_length=250, verbose_name='Facebook')),
                ('instagram_url', models.CharField(blank=True, default='', max_length=250, verbose_name='Instagram')),
                ('twitter_url', models.CharField(blank=True, default='', max_length=250, verbose_name='X / Twitter')),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=250, verbose_name='LinkedIn')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=15, verbose_name='WhatsApp')),
                ('contact_email', models.CharField(blank=True, default='', max_length=100, verbose_name='Correo de contacto')),
            ],
            options={
                'verbose_name': 'Página Informativa',
                'verbose_name_plural': 'Página Informativa',
                'permissions': (('view_marketingpage', 'Can view Página Informativa'), ('change_marketingpage', 'Can change Página Informativa')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('image', core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen')),
                ('link_text', models.CharField(blank=True, default='', max_length=50, verbose_name='Texto del enlace')),
                ('link_url', models.CharField(blank=True, default='', max_length=250, verbose_name='Enlace')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['order', 'id'],
            },
        ),
    ]
