# Generated by Django 4.2.30 on 2026-10-05 19:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('account_type', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('costo', 'Costo'), ('gasto', 'Gasto')], max_length=20, verbose_name='Tipo')),
                ('accepts_movement', models.BooleanField(default=True, verbose_name='Acepta movimientos')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_system', models.BooleanField(default=False, verbose_name='De sistema')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='contabilidad.account', verbose_name='Cuenta padre')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Plan de cuentas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio de la contabilidad')),
                ('next_entry_number', models.PositiveIntegerField(default=1)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Activada el')),
            ],
            options={
                'verbose_name': 'Configuración contable',
                'verbose_name_plural': 'Configuración contable',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banco')),
                ('number', models.CharField(max_length=30, verbose_name='Número de cuenta')),
                ('account_type', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], default='ahorros', max_length=20, verbose_name='Tipo de cuenta')),
                ('holder', models.CharField(blank=True, default='', max_length=150, verbose_name='Titular')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='contabilidad.account', verbose_name='Cuenta contable')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha contable')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado el')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado el')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('source_type', models.CharField(choices=[('sale', 'Venta'), ('credit_note', 'Nota de crédito'), ('collection', 'Cobro de cuenta por cobrar'), ('retention', 'Retención recibida'), ('purchase', 'Compra'), ('supplier_payment', 'Pago a proveedor'), ('expense', 'Gasto'), ('income', 'Ingreso'), ('cash_closing', 'Cierre de caja'), ('payroll', 'Nómina'), ('bank_move', 'Movimiento bancario'), ('manual', 'Asiento manual')], db_index=True, max_length=20, verbose_name='Origen')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('status', models.CharField(choices=[('posted', 'Registrado'), ('voided', 'Anulado')], db_index=True, default='posted', max_length=10, verbose_name='Estado')),
                ('void_reason', models.CharField(blank=True, default='', max_length=200)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Debe')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Haber')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Detalle')),
                ('third_party', models.CharField(blank=True, default='', max_length=200, verbose_name='Tercero')),
                ('third_party_id', models.CharField(blank=True, default='', max_length=20, verbose_name='Identificación')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='contabilidad.account', verbose_name='Cuenta')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='contabilidad.bankaccount', verbose_name='Cuenta bancaria')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contabilidad.journalentry')),
            ],
            options={
                'verbose_name': 'Línea de asiento',
                'verbose_name_plural': 'Líneas de asiento',
            },
        ),
        migrations.CreateModel(
            name='BankAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True, verbose_name='Texto tal como se escribe en el POS')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='contabilidad.bankaccount', verbose_name='Cuenta bancaria')),
            ],
            options={
                'verbose_name': 'Alias de banco',
                'verbose_name_plural': 'Alias de bancos',
            },
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('caja', 'Caja general'), ('banco_defecto', 'Banco por defecto'), ('tarjetas', 'Tarjetas de crédito por cobrar'), ('clientes', 'Clientes (cuentas por cobrar)'), ('proveedores', 'Proveedores (cuentas por pagar)'), ('inventario', 'Inventario de mercaderías'), ('iva_compras', 'Crédito tributario IVA en compras'), ('ret_iva', 'IVA retenido por clientes'), ('ret_renta', 'Impuesto a la renta retenido por clientes'), ('iva_ventas', 'IVA cobrado en ventas'), ('sueldos_pagar', 'Sueldos por pagar'), ('descuentos_nomina', 'Descuentos de nómina por pagar'), ('ventas_gravadas', 'Ventas con IVA'), ('ventas_0', 'Ventas tarifa 0%'), ('devoluciones', 'Devoluciones en ventas'), ('ingreso_defecto', 'Otros ingresos (por defecto)'), ('sobrante_caja', 'Sobrante de caja'), ('costo_ventas', 'Costo de ventas'), ('compras_no_inv', 'Compras no inventariables'), ('sueldos_gasto', 'Sueldos y salarios (gasto)'), ('gasto_defecto', 'Gastos generales (por defecto)'), ('gasto_bancario', 'Gastos bancarios'), ('faltante_caja', 'Faltante de caja'), ('redondeo', 'Ajuste por redondeo')], max_length=30, unique=True, verbose_name='Rol')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.account', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta por rol',
                'verbose_name_plural': 'Cuentas por rol',
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('month', models.PositiveIntegerField(verbose_name='Mes')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', max_length=10, verbose_name='Estado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrado el')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Período contable',
                'verbose_name_plural': 'Períodos contables',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='TypeAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], max_length=10)),
                ('type_id', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.account', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta por tipo',
                'verbose_name_plural': 'Cuentas por tipo',
                'unique_together': {('kind', 'type_id')},
            },
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(check=models.Q(('credit__gte', 0), ('debit__gte', 0), models.Q(('debit', 0), ('credit', 0), _connector='OR')), name='contabilidad_line_debit_xor_credit'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('bank_name', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('year', 'month')},
        ),
    ]
