# Generated by Django 4.2.30 on 2026-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='N° de comprobante'),
        ),
    ]
