# Generated by Django 4.2.30 on 2026-10-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_journalentry_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmapping',
            name='role',
            field=models.CharField(choices=[('caja', 'Caja general'), ('banco_defecto', 'Banco por defecto'), ('tarjetas', 'Tarjetas de crédito por cobrar'), ('clientes', 'Clientes (cuentas por cobrar)'), ('proveedores', 'Proveedores (cuentas por pagar)'), ('inventario', 'Inventario de mercaderías'), ('iva_compras', 'Crédito tributario IVA en compras'), ('ret_iva', 'IVA retenido por clientes'), ('ret_renta', 'Impuesto a la renta retenido por clientes'), ('iva_ventas', 'IVA cobrado en ventas'), ('ret_iva_pagar', 'Retención de IVA por pagar (al SRI)'), ('ret_renta_pagar', 'Retención en la fuente de renta por pagar (al SRI)'), ('sueldos_pagar', 'Sueldos por pagar'), ('descuentos_nomina', 'Descuentos de nómina por pagar'), ('ventas_gravadas', 'Ventas con IVA'), ('ventas_0', 'Ventas tarifa 0%'), ('devoluciones', 'Devoluciones en ventas'), ('ingreso_defecto', 'Otros ingresos (por defecto)'), ('sobrante_caja', 'Sobrante de caja'), ('costo_ventas', 'Costo de ventas'), ('compras_no_inv', 'Compras no inventariables'), ('sueldos_gasto', 'Sueldos y salarios (gasto)'), ('gasto_defecto', 'Gastos generales (por defecto)'), ('gasto_bancario', 'Gastos bancarios'), ('faltante_caja', 'Faltante de caja'), ('redondeo', 'Ajuste por redondeo')], max_length=30, unique=True, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('credit_note', 'Nota de crédito'), ('collection', 'Cobro de cuenta por cobrar'), ('retention', 'Retención recibida'), ('issued_retention', 'Retención emitida'), ('purchase', 'Compra'), ('supplier_payment', 'Pago a proveedor'), ('expense', 'Gasto'), ('income', 'Ingreso'), ('cash_closing', 'Cierre de caja'), ('payroll', 'Nómina'), ('bank_move', 'Movimiento bancario'), ('manual', 'Asiento manual')], db_index=True, max_length=20, verbose_name='Origen'),
        ),
    ]
