# Generated by Django 4.2.30 on 2026-10-06 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0003_issued_retention_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Desde')),
                ('date_to', models.DateField(verbose_name='Hasta')),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo inicial según el banco')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo final según el banco')),
                ('file_name', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='excel', max_length=10)),
                ('status', models.CharField(choices=[('open', 'En proceso'), ('reconciled', 'Conciliado')], db_index=True, default='open', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='contabilidad.bankaccount', verbose_name='Cuenta bancaria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conciliación bancaria',
                'verbose_name_plural': 'Conciliaciones bancarias',
                'ordering': ['-date_to', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('reference', models.CharField(blank=True, default='', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('entry_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_match', to='contabilidad.journalentryline')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='contabilidad.bankstatement')),
            ],
            options={
                'verbose_name': 'Movimiento del estado de cuenta',
                'verbose_name_plural': 'Movimientos del estado de cuenta',
                'ordering': ['date', 'id'],
            },
        ),
    ]
