# Generated by Django 4.2.30 on 2026-10-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_bank_statements'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='is_opening',
            field=models.BooleanField(default=False),
        ),
    ]
