[program:invoicepro]
command= /home/globalcontrolec/invoicepro/deploy/sh/gunicorn.sh
user=globalcontrolec
stdout_logfile= /home/globalcontrolec/invoicepro/logs/supervisor.log
redirect_stderr= true
autostart= true
autorestart= true
environment=LANG= en_US.UTF-8,LC_ALL=en_US.UTF-8
