# Generated by Django 4.0.2 on 2026-07-01 03:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de asistencia')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=0)),
                ('day', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'permissions': (('view_assistance', 'Can view Asistencia | Admin'), ('add_assistance', 'Can add Asistencia | Admin'), ('change_assistance', 'Can change Asistencia | Admin'), ('delete_assistance', 'Can delete Asistencia | Admin'), ('view_employee_assistance', 'Can view Asistencia | Empleado')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssistanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Detalle de Asistencia',
                'verbose_name_plural': 'Detalles de Asistencia',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Código de empleado')),
                ('dni', models.CharField(max_length=13, unique=True, verbose_name='Número de documento')),
                ('hiring_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de ingreso')),
                ('remuneration', models.FloatField(default=0.0, verbose_name='Remuneración')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Referencia')),
                ('type', models.CharField(choices=[('haberes', 'HABERES'), ('descuentos', 'DESCUENTOS')], default='haberes', max_length=15, verbose_name='Tipo')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('order', models.IntegerField(default=0, verbose_name='Posición')),
                ('has_quantity', models.BooleanField(default=False, verbose_name='¿Posee cantidad?')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de pago')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(choices=[('', '-----------'), (1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default=0, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Salario',
                'verbose_name_plural': 'Salarios',
                'permissions': (('view_salary', 'Can view Salario | Admin'), ('add_salary', 'Can add Salario | Admin'), ('change_salary', 'Can change Salario | Admin'), ('delete_salary', 'Can delete Salario | Admin'), ('view_employee_salary', 'Can view Salario | Empleado')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField(default=0.0)),
                ('expenses', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.employee', verbose_name='Empleado')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.salary')),
            ],
            options={
                'verbose_name': 'Salario Detalle',
                'verbose_name_plural': 'Salario Detalles',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalaryHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(default=0)),
                ('valor', models.FloatField(default=0.0)),
                ('headings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.headings')),
                ('salary_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.salarydetail')),
            ],
            options={
                'verbose_name': 'Detalle de Salario',
                'verbose_name_plural': 'Detalle de Salarios',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rrhh.position', verbose_name='Cargo'),
        ),
    ]
