# Generated by Django 4.2.30 on 2026-09-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='remuneration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Remuneración'),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salarydetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='salaryheadings',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
