# Generated by Django 4.2.30 on 2026-09-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_alter_employee_remuneration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancedetail',
            name='check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AddField(
            model_name='assistancedetail',
            name='check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
    ]
