# Generated by Django 4.2.30 on 2026-09-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_assistancedetail_check_in_assistancedetail_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='Horas de descanso/almuerzo'),
        ),
    ]
