# Generated by Django 4.2.30 on 2026-09-02 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_employee_break_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='scheduled_check_in',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Hora de entrada programada'),
        ),
        migrations.AddField(
            model_name='employee',
            name='scheduled_check_out',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Hora de salida programada'),
        ),
    ]
