# Generated by Django 4.0.2 on 2026-08-31 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='receipt',
            field=models.ForeignKey(blank=True, limit_choices_to={'voucher_type': 'COT'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.receipt', verbose_name='Tipo de comprobante'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='voucher_number',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Número de comprobante'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='voucher_number_full',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número de comprobante completo'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='voucher_type',
            field=models.CharField(choices=[('01', 'FACTURA'), ('04', 'NOTA DE CRÉDITO'), ('08', 'TICKET DE VENTA'), ('COT', 'COTIZACIÓN')], max_length=10, verbose_name='Tipo de Comprobante'),
        ),
    ]
