# Generated by Django 4.0.2 on 2026-08-31 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_backfill_quotation_receipt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity_days',
            field=models.PositiveIntegerField(default=15, verbose_name='Días de validez'),
        ),
        migrations.AddField(
            model_name='sale',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de elaboración'),
        ),
    ]
