# Generated by Django 4.2.30 on 2026-09-02 06:06

import core.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_remove_purchasedetail_dscto_product_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
    ]
