# Generated by Django 4.2.30 on 2026-09-02 06:56

import core.security.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0011_alter_creditnote_pdf_authorized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('nota_credito', 'Nota de Crédito'), ('ajuste', 'Ajuste Manual'), ('eliminacion', 'Eliminación de Comprobante')], max_length=20, verbose_name='Tipo de movimiento')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('stock_before', models.IntegerField(verbose_name='Stock antes')),
                ('stock_after', models.IntegerField(verbose_name='Stock después')),
                ('reference', models.CharField(max_length=200, verbose_name='Referencia')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='Motivo')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product', verbose_name='Producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario (Kardex)',
                'permissions': (('view_inventorymovement', 'Can view Movimiento de Inventario'),),
                'default_permissions': (),
            },
        ),
    ]
