# Generated by Django 4.2.30 on 2026-09-03 02:54

import core.security.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0012_alter_creditnote_pdf_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsctacollect',
            name='bank_entity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad bancaria'),
        ),
        migrations.AddField(
            model_name='paymentsctacollect',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de transferencia/cheque'),
        ),
        migrations.AddField(
            model_name='paymentsdebtspay',
            name='bank_entity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad bancaria'),
        ),
        migrations.AddField(
            model_name='paymentsdebtspay',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsdebtspay',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('deposit', 'Deposito'), ('transfer', 'Transferencia'), ('check', 'Cheque')], default='cash', max_length=50, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='paymentsdebtspay',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de transferencia/cheque'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.AlterField(
            model_name='paymentsctacollect',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('deposit', 'Deposito'), ('transfer', 'Transferencia'), ('check', 'Cheque')], default='cash', max_length=50, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='voucher_type',
            field=models.CharField(choices=[('01', 'FACTURA'), ('04', 'NOTA DE CRÉDITO'), ('08', 'TICKET DE VENTA'), ('COT', 'COTIZACIÓN'), ('03', 'LIQUIDACIÓN DE COMPRA')], max_length=10, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
    ]
