# Generated by Django 4.2.30 on 2026-09-03 03:06

import core.security.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0013_paymentsctacollect_bank_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('opening_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora de apertura')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor de apertura')),
                ('opening_notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones de apertura')),
                ('closing_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de cierre')),
                ('counted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Efectivo contado')),
                ('expected_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Efectivo esperado')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Diferencia')),
                ('breakdown', models.JSONField(blank=True, default=dict, verbose_name='Detalle del cuadre')),
                ('closing_notes', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones de cierre')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=10, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'permissions': (('view_cashregister', 'Can view Caja'),),
                'default_permissions': (),
            },
        ),
    ]
