# Generated by Django 4.2.30 on 2026-09-03 04:07

import core.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_cashregister_opening_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='card_authorization_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de autorización'),
        ),
        migrations.AddField(
            model_name='sale',
            name='card_owner_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula/RUC del propietario de la tarjeta'),
        ),
        migrations.AddField(
            model_name='sale',
            name='card_transaction_type',
            field=models.CharField(blank=True, choices=[('corriente', 'Corriente'), ('diferido', 'Diferido')], max_length=20, null=True, verbose_name='Tipo de transacción'),
        ),
        migrations.AddField(
            model_name='sale',
            name='card_type',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('diners', 'Diners Club'), ('american_express', 'American Express'), ('discover', 'Discover')], max_length=50, null=True, verbose_name='Tipo de tarjeta'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transfer_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entidad bancaria'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transfer_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de transferencia'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Código de barra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=core.security.fields.CustomImageField(blank=True, null=True, upload_to=core.security.fields.CustomImageField.get_upload_path, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Credito'), ('transferencia', 'Transferencia'), ('tarjeta_credito', 'Tarjeta de Crédito')], default='efectivo', max_length=50, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pdf_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='PDF Autorizado'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='xml_authorized',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.CustomFileField.get_upload_path, verbose_name='XML Autorizado'),
        ),
    ]
