# Generated by Django 4.2.30 on 2026-09-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_sale_card_authorization_number_sale_card_owner_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.sale', verbose_name='Venta generada'),
        ),
    ]
