# Generated by Django 4.2.30 on 2026-09-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_quotation_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='next_opening_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor dejado para la próxima apertura'),
        ),
    ]
