# Generated by Django 4.2.30 on 2026-09-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_cashregister_next_opening_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('dscto', models.DecimalField(decimal_places=4, default=0.0, max_digits=9, verbose_name='Descuento')),
                ('active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'permissions': (('view_combo', 'Can view Combo'), ('add_combo', 'Can add Combo'), ('change_combo', 'Can change Combo'), ('delete_combo', 'Can delete Combo')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComboDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.combo', verbose_name='Combo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle Combo',
                'verbose_name_plural': 'Detalle de Combos',
                'default_permissions': (),
            },
        ),
    ]
