# Generated by Django 4.2.30 on 2026-09-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_combo_combodetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='credit_card_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio tarjeta de crédito'),
        ),
        migrations.AddField(
            model_name='combo',
            name='pvp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio al público'),
        ),
        migrations.AddField(
            model_name='combo',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio distribuidor'),
        ),
    ]
