# Generated by Django 4.2.30 on 2026-09-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_combo_credit_card_price_combo_pvp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('retail', 'Público'), ('wholesale', 'Distribuidor'), ('credit_card', 'Tarjeta de Crédito')], max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Precio',
                'verbose_name_plural': 'Tipos de Precio',
                'permissions': (('view_price_type', 'Can view Tipo de Precio'), ('change_price_type', 'Can change Tipo de Precio')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='manual_price',
            field=models.BooleanField(default=False, verbose_name='Precio de venta manual'),
        ),
        migrations.AlterField(
            model_name='client',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Público'), ('wholesale', 'Distribuidor'), ('credit_card', 'Tarjeta de Crédito')], default='retail', max_length=30, verbose_name='Tipo de Precio de Venta'),
        ),
    ]
