# Generated by Django 4.2.30 on 2026-09-09 03:48

from django.db import migrations, models


def set_manual_price_true(apps, schema_editor):
    # Revierte el default anterior (False): todos los productos ya
    # existentes en este esquema quedan editables, igual que los nuevos.
    Product = apps.get_model('pos', 'Product')
    Product.objects.update(manual_price=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_pricetype_product_manual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manual_price',
            field=models.BooleanField(default=True, verbose_name='Precio de venta manual'),
        ),
        migrations.RunPython(set_manual_price_true, noop),
    ]
