# Generated by Django 4.2.30 on 2026-09-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_alter_product_manual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='authorization_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de autorización'),
        ),
    ]
