# Generated by Django 4.2.30 on 2026-09-12 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0023_alter_sale_authorization_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y hora de registro'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='ctascollect',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='debtspay',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='paymentsctacollect',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='paymentsdebtspay',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
    ]
