# Generated by Django 4.2.30 on 2026-09-12 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0024_quotation_creation_date_alter_creditnote_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients_registered', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
