# Generated by Django 4.2.30 on 2026-09-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de cliente'),
        ),
    ]
