# Generated by Django 4.2.30 on 2026-09-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_client_client_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de cliente'),
        ),
    ]
