# Generated by Django 4.2.30 on 2026-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_alter_client_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='additional_info',
            field=models.JSONField(default=dict, verbose_name='Información adicional'),
        ),
    ]
