# Generated by Django 4.2.30 on 2026-09-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_creditnote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('deposit', 'Deposito'), ('transfer', 'Transferencia'), ('check', 'Cheque')], default='cash', max_length=50, verbose_name='Forma de devolución'),
        ),
    ]
