# Generated by Django 4.2.30 on 2026-09-19 03:17

import core.security.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_company_default_sale_voucher_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0030_creditnote_refund_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de registro')),
                ('issue_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de emisión')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de comprobante')),
                ('access_code', models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de acceso')),
                ('agent_ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC del agente de retención')),
                ('agent_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Razón social del agente de retención')),
                ('iva_retained', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA retenido')),
                ('income_tax_retained', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Renta retenida')),
                ('total_retained', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total retenido')),
                ('xml_file', core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.UploadTo(None, None), verbose_name='XML del comprobante')),
                ('observations', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.company', verbose_name='Compañia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
                'permissions': (('view_retention', 'Can view Retención'), ('add_retention', 'Can add Retención'), ('delete_retention', 'Can delete Retención')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='paymentsctacollect',
            name='retention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.retention', verbose_name='Retención aplicada'),
        ),
    ]
