# Generated by Django 4.2.30 on 2026-09-24 05:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0031_retention_paymentsctacollect_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Ingreso',
                'verbose_name_plural': 'Tipos de Ingresos',
                'permissions': (('view_type_income', 'Can view Tipo de Ingreso'), ('add_type_income', 'Can add Tipo de Ingreso'), ('change_type_income', 'Can change Tipo de Ingreso'), ('delete_type_income', 'Can delete Tipo de Ingreso')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='expenses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('type_income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.typeincome', verbose_name='Tipo de Ingreso')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'permissions': (('view_income', 'Can view Ingreso'), ('add_income', 'Can add Ingreso'), ('change_income', 'Can change Ingreso'), ('delete_income', 'Can delete Ingreso')),
                'default_permissions': (),
            },
        ),
    ]
