# Generated by Django 4.2.30 on 2026-10-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_typeincome_expenses_created_by_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('deposit', 'Deposito'), ('transfer', 'Transferencia'), ('check', 'Cheque')], default='cash', max_length=50, verbose_name='Forma de pago'),
        ),
    ]
