# Generated by Django 4.2.30 on 2026-10-01 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_income_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='date_joined',
            field=models.DateField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], db_index=True, default='open', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('without_authorizing', 'Sin Autorizar'), ('authorized', 'Autorizada'), ('authorized_and_sent_by_email', 'Autorizada y enviada por email'), ('canceled', 'Anulado'), ('sequential_registered_error', 'Error de secuencial registrado')], db_index=True, default='without_authorizing', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ctascollect',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='debtspay',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='paymentsctacollect',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='paymentsdebtspay',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date_joined',
            field=models.DateField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de elaboración'),
        ),
        migrations.AlterField(
            model_name='retention',
            name='date_joined',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(db_index=True, default=datetime.datetime.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('without_authorizing', 'Sin Autorizar'), ('authorized', 'Autorizada'), ('authorized_and_sent_by_email', 'Autorizada y enviada por email'), ('canceled', 'Anulado'), ('sequential_registered_error', 'Error de secuencial registrado')], db_index=True, default='without_authorizing', max_length=50, verbose_name='Estado'),
        ),
    ]
