# Generated by Django 4.2.30 on 2026-10-05 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F
from django.db.models.functions import TruncDate


def backfill_existing_purchases(apps, schema_editor):
    """Las compras anteriores se registraron SIN IVA: su total es su subtotal,
    toda su base es 0 % y la fecha de emisión se toma de la de registro. Así
    ningún listado ni reporte histórico cambia de valor."""
    Purchase = apps.get_model('pos', 'Purchase')
    Purchase.objects.update(
        total=F('subtotal'),
        subtotal_0=F('subtotal'),
        issue_date=TruncDate('date_joined'),
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0034_alter_cashregister_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='id_type',
            field=models.CharField(choices=[('01', 'RUC'), ('02', 'Cédula'), ('03', 'Pasaporte / identificación del exterior')], default='01', max_length=2, verbose_name='Tipo de identificación'),
        ),
        migrations.AddField(
            model_name='provider',
            name='related_party',
            field=models.BooleanField(default=False, verbose_name='Parte relacionada'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='authorization_number',
            field=models.CharField(blank=True, default='', max_length=49, verbose_name='Número de autorización'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de emisión del comprobante'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('01', 'SIN UTILIZACION DEL SISTEMA FINANCIERO'), ('15', 'COMPENSACIÓN DE DEUDAS'), ('16', 'TARJETA DE DÉBITO'), ('17', 'DINERO ELECTRÓNICO'), ('18', 'TARJETA PREPAGO'), ('20', 'OTROS CON UTILIZACION DEL SISTEMA FINANCIERO'), ('21', 'ENDOSO DE TÍTULOS')], default='01', max_length=50, verbose_name='Forma de pago (SRI)'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='subtotal_0',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base IVA 0%'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='subtotal_exempt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base exenta de IVA'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='subtotal_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base con IVA'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='subtotal_no_object',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base no objeto de IVA'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax_support',
            field=models.CharField(choices=[('01', '01 - Crédito tributario IVA (servicios y bienes que no son inventario ni activo fijo)'), ('02', '02 - Costo o gasto para IR (servicios y bienes que no son inventario ni activo fijo)'), ('03', '03 - Activo fijo: crédito tributario IVA'), ('04', '04 - Activo fijo: costo o gasto para IR'), ('05', '05 - Liquidación de gastos de viaje, hospedaje y alimentación (IR)'), ('06', '06 - Inventario: crédito tributario IVA'), ('07', '07 - Inventario: costo o gasto para IR'), ('08', '08 - Valor pagado para solicitar reembolso de gasto (intermediario)'), ('09', '09 - Reembolso por siniestros'), ('10', '10 - Distribución de dividendos, beneficios o utilidades'), ('11', '11 - Convenios de débito o recaudación para IFI'), ('12', '12 - Impuestos y retenciones presuntivos'), ('13', '13 - Valores reconocidos por entidades del sector público'), ('00', '00 - Caso especial cuyo sustento no aplica en las opciones anteriores')], default='06', max_length=2, verbose_name='Sustento tributario'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='voucher_type',
            field=models.CharField(choices=[('01', 'Factura'), ('02', 'Nota o boleta de venta'), ('09', 'Tiquete de máquina registradora'), ('12', 'Documento emitido por institución financiera'), ('15', 'Comprobante de venta emitido en el exterior'), ('18', 'Documento autorizado utilizado en ventas (excepto N/C y N/D)'), ('19', 'Comprobante de pago de cuotas o aportes'), ('20', 'Documento por servicios administrativos de institución del Estado')], default='01', max_length=3, verbose_name='Tipo de comprobante'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='iva_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tarifa de IVA (%)'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='tax_type',
            field=models.CharField(choices=[('iva', 'IVA'), ('0', 'IVA 0%'), ('no_objeto', 'No objeto de IVA'), ('exento', 'Exento de IVA')], default='0', max_length=10, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.RunPython(backfill_existing_purchases, migrations.RunPython.noop),
    ]
