# Generated by Django 4.2.30 on 2026-10-05 21:10

import core.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_purchase_iva_and_voucher_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='access_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=49, verbose_name='Clave de acceso'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='authorization_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='xml_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos leídos del XML'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='xml_file',
            field=core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.UploadTo(None, None), verbose_name='XML del proveedor'),
        ),
    ]
