# Generated by Django 4.2.30 on 2026-10-05 21:44

import core.security.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0010_company_default_sale_voucher_type'),
        ('pos', '0036_purchase_xml_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('renta', 'Impuesto a la renta'), ('iva', 'IVA')], max_length=5, verbose_name='Impuesto')),
                ('code', models.CharField(max_length=5, verbose_name='Código SRI')),
                ('description', models.CharField(max_length=300, verbose_name='Concepto')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje (%)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Nota del catálogo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Concepto de retención',
                'verbose_name_plural': 'Conceptos de retención',
                'ordering': ['kind', 'code'],
                'permissions': (('view_retention_concept', 'Can view Concepto de retención'), ('add_retention_concept', 'Can add Concepto de retención'), ('change_retention_concept', 'Can change Concepto de retención'), ('delete_retention_concept', 'Can delete Concepto de retención')),
                'default_permissions': (),
                'unique_together': {('kind', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SupplierRetention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=9, verbose_name='Número de comprobante')),
                ('voucher_number_full', models.CharField(max_length=20, verbose_name='Número de comprobante completo')),
                ('date_joined', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Fecha de emisión')),
                ('environment_type', models.PositiveIntegerField(choices=[(1, 'PRUEBAS'), (2, 'PRODUCCIÓN')], default=1)),
                ('access_code', models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de acceso')),
                ('authorization_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de autorización')),
                ('xml_authorized', core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.UploadTo(None, None), verbose_name='XML Autorizado')),
                ('pdf_authorized', core.security.fields.CustomFileField(blank=True, null=True, upload_to=core.security.fields.UploadTo(None, None), verbose_name='PDF Autorizado')),
                ('status', models.CharField(choices=[('without_authorizing', 'Sin Autorizar'), ('authorized', 'Autorizada'), ('authorized_and_sent_by_email', 'Autorizada y enviada por email'), ('canceled', 'Anulado'), ('sequential_registered_error', 'Error de secuencial registrado')], db_index=True, default='without_authorizing', max_length=50, verbose_name='Estado')),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA retenido')),
                ('total_renta', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Renta retenida')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total retenido')),
                ('observations', models.CharField(blank=True, default='', max_length=300, verbose_name='Observaciones')),
                ('idempotency_key', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Llave de idempotencia')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.company', verbose_name='Compañia')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.provider', verbose_name='Proveedor')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Retención emitida',
                'verbose_name_plural': 'Retenciones emitidas',
                'permissions': (('view_supplier_retention', 'Can view Retención emitida'), ('add_supplier_retention', 'Can add Retención emitida'), ('delete_supplier_retention', 'Can delete Retención emitida')),
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='receipt',
            name='voucher_type',
            field=models.CharField(choices=[('01', 'FACTURA'), ('04', 'NOTA DE CRÉDITO'), ('08', 'TICKET DE VENTA'), ('COT', 'COTIZACIÓN'), ('03', 'LIQUIDACIÓN DE COMPRA'), ('07', 'COMPROBANTE DE RETENCIÓN')], max_length=10, verbose_name='Tipo de Comprobante'),
        ),
        migrations.CreateModel(
            name='SupplierRetentionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Base imponible')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentaje (%)')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor retenido')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.retentionconcept', verbose_name='Concepto')),
                ('retention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.supplierretention')),
            ],
            options={
                'verbose_name': 'Detalle de retención emitida',
                'verbose_name_plural': 'Detalles de retención emitida',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='supplierretention',
            name='receipt',
            field=models.ForeignKey(limit_choices_to={'voucher_type': '07'}, on_delete=django.db.models.deletion.PROTECT, to='pos.receipt', verbose_name='Tipo de comprobante'),
        ),
        migrations.AddField(
            model_name='paymentsdebtspay',
            name='supplier_retention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.supplierretention', verbose_name='Retención aplicada'),
        ),
    ]
